Allow header, path and query param parsers to allow interfaces and type references
zenclabs/api pull request #1022
Opened 2020-09-20 06:41 UTC by mahirk

## Description, Motivation and Context
Resolves: https://github.com/airtasker/spot/issues/1009

Allows the declaration of re-usable interfaces and types for headers and parameters so that the following style can be used
```
    request(
        @headers
        headers: SomeTypeHere,
        @pathParams
        pathParams: SomeOtherTypeHere
    ) {}
```
instead of:
```
    request(
        @headers
        headers: { someString: string; },
        @pathParams
        pathParams: { someOtherString: string; }
    ) {}
```

This was also tested locally by extending the definition in the README to:
```
class CreateUser {
  @request
  request(
    @headers
    headers: IHeader,
    @pathParams
    pathParams: PathParams,
    @body body: CreateUserRequest
  ) {}

  @response({ status: 201 })
  successResponse(@body body: CreateUserResponse) {}
}

interface IHeader {
  /** Header for XYZ ABC Purposes */
  someString: string;
}

type PathParams = {
  /** Extra path params for fun */
  someOtherString: string;
};

```

This resulted in the following spec:
```
post:
      operationId: CreateUser
      parameters:
        - name: someOtherString
          in: path
          description: Extra path params for fun
          required: true
          schema:
            type: string
        - name: someString
          in: header
          description: Header for XYZ ABC Purposes
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        required: true
```

The method was changed so that it is still able to retrieve property signatures from the type to allow it to decorate the parameters in a correct manner. The error message was also updated to maintain the new style of parameters accepted. For this reason, TypeReference->TypeAlias->TypeReference->...->Declaration are not supported, for example:
```
interface RequestSecret {
    'x-api-signing-key': string;
}

type SecondaryTypeAlias = RequestSecret

class GetRequestSample {
    @request
    request(
        @headers
        headers: SecondaryTypeAlias,
    ) {}

    @response({ status: 200 })
    response(@body body: SomeResponseBody) {}
}
```

Will fail from compiling, since as per the AST no property signatures are available at that level

## Checklist:

- [x] I've added/updated tests to cover my changes
- [x] I've created an issue associated with this PR

2020-09-22 05:57 UTC, mahirk commented
Tagging @lfportal @committedteadrinker for potential review on this :)

2020-09-23 14:00 UTC, lfportal requested changes
Looks good. Thanks @mahirk! Couple of clarifications and I think we should we able to support type alias references without much additional effort.

2020-09-23 21:06 UTC, mahirk commented on lib/src/parsers/parser-helpers.ts
> +  }
@lfportal Interesting! I should've tested it out when I was exploring the AST, it didn't allow me to draw that parallel. I have updated the PR to allow that, as well as cleaned up the code slightly to allow some sharing of functions.

2020-09-24 01:35 UTC, lfportal approved these changes
Looks good, thanks @mahirk!

2020-09-24 01:36 UTC, merged