Introduce Int32 and Int64 type aliases
zenclabs/api pull request #219
Opened 2019-05-09 00:30 UTC by fwouts

This reshuffles how we handle number types in Spot:
- NUMBER is renamed to FLOAT internally for clarity (still mapped to both `number` and `Float` in TypeScript)
- INTEGER is renamed to INT32 internally (mapped to both `Integer` and the new `Int32` TypeScript alias)
- INT64 is introduced (and mapped to the new `Int64` TypeScript alias)

See relevant discussion internally for context: https://github.com/airtasker/api-guidelines/pull/21

Happy to discuss, there are probably better approaches.

2019-05-13 04:07 UTC, lfportal approved these changes

2019-05-13 04:07 UTC, lfportal commented on lib/src/models/types/index.ts
> +  | Int32Type
What of `Int64`?

2019-05-13 04:07 UTC, lfportal commented on lib/src/models/types/kinds.ts
> +  TypeKind.INT32
What of `Int64`?

2019-05-13 04:07 UTC, lfportal commented on lib/src/parsers/utilities/type-reference-resolver.ts
> +      case TypeKind.INT32:
`INT64`?

2019-05-13 04:07 UTC, lfportal requested changes
changes in previous review

2019-05-13 04:49 UTC, lfportal commented
https://github.com/airtasker/spot/wiki/Guide#4-types will require an update as well

2019-05-13 23:42 UTC, fwouts commented
Thanks @lfportal, all addressed.

2019-05-14 00:47 UTC, lfportal approved these changes

2019-05-14 01:03 UTC, merged