Helpful error message for missing String declaration
zenclabs/api pull request #247
Opened 2019-05-27 06:40 UTC by lfportal

When using the `String` native type, the TypeScript compiler does not complain as there exists native `String` interfaces in TypeScript. However, Spot will complain with an unhelpful message. A more helpful error message has been added to help with understanding the error.

2019-05-27 06:51 UTC, fwouts approved these changes
Have you considered the alternative of simply behaving as if the import was there?

2019-05-27 06:51 UTC, fwouts requested changes
Oh also, a test would be good 🙂

2019-05-27 06:54 UTC, lfportal commented
> Have you considered the alternative of simply behaving as if the import was there?

Do you mean to accept all forms of `String`?
- typescript native
- imported from airtasker syntax
- user redefined

2019-05-27 07:08 UTC, fwouts commented
Yes, exactly. Thoughts?

2019-05-27 07:32 UTC, lfportal commented
> Yes, exactly. Thoughts?

From a purest POV, I find it odd that we let users redefine `String`. I think allowing the use of the typescript native `String` interface is fine, though it may mean more work in the parser somewhere - will need to try a few things to see what the effects are.

2019-05-28 02:24 UTC, lfportal commented
@fwouts There doesn't seem to be an elegant way to determine whether `String` is using the native TypeScript interface. We can only look at declaration file paths. There are 9 declarations of `String` in TypeScript - none of which are type-aliasing `string`. Even if we simply pick the first declaration to be used, it will error downstream when checking for whether the Spot internal `String` type has been redefined, which require creating another exception for. I think this may lead to more discrete behaviour required to handle `String` elsewhere in the code which will be harder to maintain as Spot evolves. I'm thinking that we should hold off on allowing `String` without imports until it's determined to be too much a nuisance to require importing. Thoughts?

2019-05-28 04:31 UTC, fwouts commented
You're right, in that case let's just clearly reject any missing String imports.

2019-05-28 04:31 UTC, fwouts approved these changes

2019-05-28 04:48 UTC, merged