Status and body verifier
zenclabs/api pull request #427
Opened 2019-09-09 01:04 UTC by committedteadrinker

## WHY
As part of the contract testing verification, we need to be able to verify status and body (expected from the contract vs the real code implementation).

## WHAT
Added verification private methods for status and body. Copied from the old test-runner.ts

2019-09-09 08:13 UTC, committedteadrinker commented on lib/src/neu/verifications/contract-verifier.ts
> +      results.concat(expectedEndpoint);
I am confused with kotlin, jumping around languages is fun.

2019-09-09 08:20 UTC, committedteadrinker commented on lib/src/neu/verifications/contract-verifier.ts
> +  private verifyStatus(
I think it should be accepting status code as string and compare the default as well. Should not fall back to default, no?

2019-09-09 08:20 UTC, committedteadrinker commented on lib/src/neu/verifications/contract-verifier.ts
> +   * Check if an exios response body matches the expected body of an expected response definition.
woop, need to update all the docos

2019-09-09 08:20 UTC, committedteadrinker commented on lib/src/neu/verifications/options.ts
> +  body: UserInputBody;
is body a type? I think a body can have a type and a content?

2019-09-11 00:59 UTC, lfportal commented on lib/src/neu/verifications/contract-mismatcher.ts
> +      mismatches = mismatches.concat(mismatchesOnResponseBody.unwrap());
Suggestion: rather than reassigning - `mismatches.push(...mismatchesOnResponseBody.unwrap())`

2019-09-11 01:02 UTC, lfportal commented on lib/src/neu/verifications/contract-mismatcher.ts
> +  private getRequestBodyTypeOnContractEndpoint(
an endpoint without a `request` object or request `body` is still valid

2019-09-11 01:06 UTC, lfportal approved these changes

2019-09-11 03:49 UTC, lfportal requested changes

2019-09-11 03:49 UTC, lfportal commented on lib/src/neu/verifications/contract-mismatcher.ts
> +    const replacedContractPathPattern = contractPath.replace(/:.*\//g, ".*/");
```suggestion
    const replacedContractPathPattern = contractPath.replace(/:[^\/]*/g, ".+");
```
`"/users/:userId".replace(/:.*\//g, ".*/") === "/users/:userId"`

2019-09-11 03:59 UTC, lfportal approved these changes

2019-09-11 05:24 UTC, merged