TT-541 find mismatches contract headers
zenclabs/api pull request #447
Opened 2019-09-18 04:29 UTC by committedteadrinker

## Description, Motivation and Context
This change is part of the mismatcher contract testing. This functionality is needed to verify and find mismatches on request and response header with the contract that's passed into spot.
https://airtasker.atlassian.net/browse/TT-541

## Checklist:

- [x] I've added/updated tests to cover my changes
- [x] I've created an issue associated with this PR

2019-09-18 05:01 UTC, lfportal requested changes

2019-09-18 09:05 UTC, alephao reviewed
It looks like the `Error` case of the `Result` type is not very useful for most cases since you're always transforming an `Error` into a `Mismatch` in the end.

I believe that the `Result` type might not be the best abstraction for our use case, in the future would be good to explore other ideas like the `Validated` type

2019-09-18 22:25 UTC, committedteadrinker commented on lib/src/neu/verifications/contract-mismatcher.ts
> +  private findMismatchOnResponseHeader(
Like the above, the endpoint path and method are needed for the error messages, I can unbox the object and pass in as 3 separate parameters if you want.

2019-09-19 01:06 UTC, committedteadrinker commented on lib/src/neu/verifications/contract-mismatcher.ts
> +        if (contractResponse.status === userInputResponse.statusCode) {
I updated the method for reusability.

2019-09-19 01:07 UTC, committedteadrinker commented
Agreed with you @alephao I think we should revisit the structure of that later on. Though if some methods are returning `Result<>` I think the others should do too? It's to keep consistency across the whole file.

2019-09-19 01:37 UTC, lfportal approved these changes

2019-09-19 01:37 UTC, alephao commented
@committedteadrinker I know you're just following the current structure, we should definitely keep consistency. I just wanted to highlight the problem, but it's not really specific to this PR.

2019-09-19 01:37 UTC, alephao approved these changes

2019-09-19 01:39 UTC, merged