Add contextual data to validation server error messages
zenclabs/api pull request #528
Opened 2019-11-01 02:58 UTC by lfportal

## Description, Motivation and Context
The messages returned from validation server currently contain very little contextual data to aid in resolving contract violations. This PR adds some contextual data including:
- Details when a type violation occurs
- The received interaction (request/response)
- The `endpoint` matched

## Checklist:

- [x] I've added/updated tests to cover my changes
- [] I've created an issue associated with this PR

2019-11-04 06:20 UTC, alephao requested changes
In some places, you're using a function to create the violation object, but in other places you're using the object initializer `new MyObject(...)`. Is there a reason for that? If not, can we use only one way for consistency?

I highlighted some examples in the comments below

2019-11-04 06:20 UTC, alephao commented on lib/src/neu/verifications/contract-mismatcher.ts
> +          mismatches.push(new UndefinedHeader(iH.name));
Same here
```suggestion
          mismatches.push(undefinedHeader(iH.name));
```

2019-11-04 06:20 UTC, alephao commented on lib/src/neu/verifications/contract-mismatcher.ts
> +            new PathParamTypeMismatch(
```suggestion
            pathParamTypeMismatch(
```

2019-11-04 06:20 UTC, alephao commented on lib/src/neu/verifications/contract-mismatcher.ts
> +        return ok([new UndefinedBody()]);
```suggestion
        return ok([undefinedBody()]);
```

2019-11-04 06:20 UTC, alephao commented on lib/src/neu/verifications/contract-mismatcher.ts
> +          new QueryParamTypeMismatch(
```suggestion
          queryParamTypeMismatch(
```

2019-11-04 06:20 UTC, alephao commented on lib/src/neu/verifications/contract-mismatcher.ts
> +        mismatches.push(new UndefinedQueryParam(key));
```suggestion
        mismatches.push(undefinedQueryParam(key));
```

2019-11-04 06:20 UTC, alephao commented on lib/src/neu/verifications/contract-mismatcher.ts
> +class QueryParamTypeMismatch {
Should these classes be moved to `violations.ts` as well? They seem to be related

2019-11-05 02:44 UTC, alephao approved these changes
Looks good, I just have a question related to naming

2019-11-05 02:44 UTC, alephao commented on lib/src/neu/verifications/mismatches.ts
> +export interface RequiredHeaderMissingMismatch {
I saw you renamed `Mismatch` to `DisparityViolation`, should the interfaces in this file also be renamed?

Look the comment below for an example👇

2019-11-05 02:44 UTC, alephao commented on lib/src/neu/verifications/mismatches.ts
> +export interface HeaderTypeDisparityMismatch {
For example, should this be `HeaderTypeDisparityViolation` instead?

2019-11-05 02:44 UTC, alephao commented on lib/src/neu/verifications/mismatches.ts
> +export interface RequiredQueryParamMissingMismatch {
And here, should it be `RequiredQueryParamMissingViolation` instead of `*MissingMismatch`?

2019-11-05 02:47 UTC, alephao commented on lib/src/neu/verifications/mismatches.ts
> +export interface RequiredHeaderMissingMismatch {
explained offline, I didn't saw the comment on the file

2019-11-05 03:03 UTC, medric approved these changes
As discussed offline, we should decouple the logic here and think about refactoring this so it's easier to follow. Maybe we could have 2 separate modules, in different files. One for input mismatches, more generic that returns mismatches objects, and one more specific to a contract violations. IMO, it would help to distinguish between `Mismatch` and `Violation`.  Can you create a ticket for this ?

2019-11-05 03:06 UTC, merged