[AUTH-22] lint validation for request objects
zenclabs/api pull request #713
Opened 2020-02-21 03:15 UTC by lemattma

## Description, Motivation and Context

- Why is this change required?
- What does it do?
It adds a linting validation for an endpoint request making sure it's an object and not a primitive or array.

## Checklist:

- [ ] I've added/updated tests to cover my changes
- [ ] I've created an issue associated with this PR

2020-02-21 03:15 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/airtasker/spot?pullRequest=713) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airtasker/spot?pullRequest=713) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airtasker/spot?pullRequest=713) it.</sub>

2020-02-21 05:31 UTC, medric commented on lib/src/linting/rules/no-primitives-in-request.ts
> +    const typeTable = TypeTable.fromArray(contract.types);
You don't have to re-instantiate the `typeTable` for every endpoint ;)

2020-02-21 05:32 UTC, medric commented on lib/src/linting/rules/no-primitives-in-request.ts
> +
```suggestion
    const typeTable = TypeTable.fromArray(contract.types);
```

2020-02-21 05:33 UTC, medric commented on lib/src/linting/rules/no-primitives-in-request.ts
> +    if (bodyType.kind !== "object") {
What about `arrays` - do they get dereferenced as objects as well?

2020-02-21 05:35 UTC, medric approved these changes
LGTM 💯  - just left a comment. Thanks for you contribution @lemattma

2020-02-22 12:46 UTC, lfportal requested changes

2020-02-22 12:46 UTC, lfportal commented on lib/src/linting/rules/no-primitives-in-request.ts
> +    if (bodyType.kind !== "object") {
For type checks, we use the type guards defined in https://github.com/airtasker/spot/blob/master/lib/src/types.ts#L353 - in this case `isObjectType(...`

2020-03-03 20:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/airtasker/spot?pullRequest=713) <br/>All committers have signed the CLA.

2020-04-09 00:22 UTC, lfportal approved these changes

2020-04-09 00:22 UTC, lfportal commented on lib/src/linting/rules/no-primitives-in-request.ts
> +    if (isObjectType(bodyType) === false) {
```suggestion
    if (!isObjectType(bodyType)) {
```

2020-04-09 00:26 UTC, merged